sudo: required
services:
  - docker

before_install:
  - docker build -t wxwwarren:react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wxwwarren:react-test npm run test

after_success:
  - docker build -t wxwwarren/multi-client:hello ./client
  - docker build -t wxwwarren/multi-nginx:hello ./nginx
  - docker build -t wxwwarren/multi-server:hello ./server
  - docker build -t wxwwarren/multi-worker:hello ./worker
  # Log in to docker CLI
  # Push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wxwwarren/multi-client:hello
  - docker push wxwwarren/multi-nginx:hello
  - docker push wxwwarren/multi-server:hello
  - docker push wxwwarren/multi-worker

